' Developer Express Code Central Example:
' How to enable MDI mode for a DocumentGroup
' 
' In this example, MDI mode is enabled for a DocumentGroup via the MDIStyle
' property. In this mode, the DocumentGroup's panels are represented as floating
' windows.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E2190
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace DocumentGroup_MDI_Ex.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As DocumentGroup_MDI_Ex.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New DocumentGroup_MDI_Ex.Properties.Settings())), DocumentGroup_MDI_Ex.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return DocumentGroup_MDI_Ex.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
